### ISSUE TITLE
I am not able to get the pf* for patterns to show.  Any suggestions? 

### ISSUE THREAD

**Issue by BoatwrightJA** [pfelk/pfelk#116]
**Describe the bug**
I a not able to get the logs ingested.  Also, the patterns does not work.  

I have done an manual install.  There were three files I could not install. 

**To Reproduce**

**Screenshots**

**Firewall System (please complete the following information):**
 - pfSense 
 - V 2.4.5
 
**Operating System (please complete the following information):**
 Linux 5.4.0-29-generic x86_64
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - Version of ELK (`dpkg -l elasticsearch|logstash|kibana`)

I was not able to complete. 

<img width="467" alt="image" src="https://user-images.githubusercontent.com/59629037/81490908-7faad900-9255-11ea-9914-7f0f6aa2dab5.png">

 
 **Elasticsearch, Logstash, Kibana logs:**
 - Elasticsearch logs (`tail -f /var/log/elasticsearch/[your-elk-cluster-name].log`)

Does not work. No path. I am not sure why its not. 

 - Logstash logs (`tail -f /var/log/logstash/logstash-plain.log`)

[log2.txt](https://github.com/3ilson/pfelk/files/4605166/log2.txt)

 - Kibana logs (`journalctl -u kibana.service`)
[log.txt](https://github.com/3ilson/pfelk/files/4605162/log.txt)

**Additional context**

**Attach the pfELK Error Log (error.pfelk), for Better Assistance***
 - Do not copy/paste log; attach as a file
[log.txt](https://github.com/3ilson/pfelk/files/4605164/log.txt)

**Comment by a3ilson** [comment]
@BoatwrightJA - What installation method did you utilize to install? Based on the provided logs, Logstash is not running (unable to located GeoIP).

**Comment by BoatwrightJA** [comment]
I did the manual install.  I finally got it to run.  However, I don't see much of the firewall and surgical logs or just the pfsense logs in general.  

<img width="1362" alt="image" src="https://user-images.githubusercontent.com/59629037/81506896-78bcae80-92c7-11ea-8877-7f73032ae4a4.png">


I also wanted to note that there was a file 11-pfsense.conf that didn't work.  Any idea?

**Comment by fktkrt** [comment]
So, yes logstash is definitely not running, probably due to missing  GeoIP databases, they should be here: `/data/pfELK/GeoIP/` as you can see in the Ubuntu installation instructions.

Regarding your package versions and logs:

- `dpkg -l elasticsearch|logstash|kibana`  is actually not one exact command, but 3 options for the 3 components. For example you can check your version of Logstash with this: `dpkg -l logstash`, sorry for the foggy instruction, I will try to clean that up in the bug/issue template

- Elasticsearch logs: that command should point to your Elasticsearch installation, ending with your configured Elasticsearch cluster name, like `pfelk.log` Make sure you adjust that as well.

Please let us know, if you had any success utilizing the geoip databases.

**Comment by BoatwrightJA** [comment]
I do have them there 
<img width="618" alt="image" src="https://user-images.githubusercontent.com/59629037/81632656-d4c32800-93d8-11ea-8144-7925294dc0c9.png">

<img width="593" alt="image" src="https://user-images.githubusercontent.com/59629037/81632720-fde3b880-93d8-11ea-95df-9fbc7781d729.png">

<img width="638" alt="image" src="https://user-images.githubusercontent.com/59629037/81632796-21a6fe80-93d9-11ea-9e0d-c0dd71f7a602.png">

<img width="667" alt="image" src="https://user-images.githubusercontent.com/59629037/81632835-37b4bf00-93d9-11ea-8399-2835149f2c8d.png">

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/59629037/81633625-2ec4ed00-93db-11ea-8148-1a1d29bd6fb2.png">

**Comment by revere521** [comment]
Please run the troubleshooting script detailed here: https://github.com/3ilson/pfelk/blob/master/install/ubuntu.md#troubleshootingAnd attach the output file here.  It will let us look at the entirety of your config to diagnose what is happeningOn May 11, 2020 11:00 PM, BoatwrightJA <notifications@github.com> wrote:
I do have them there

**Comment by BoatwrightJA** [comment]
[error-data.txt](https://github.com/3ilson/pfelk/files/4613202/error-data.txt)

**Comment by BoatwrightJA** [comment]
[error.pfelk.log](https://github.com/3ilson/pfelk/files/4613214/error.pfelk.log)

**Comment by a3ilson** [comment]
@BoatwrightJA - Based on the provided log, you have a couple of files that are in the wrong place and/or could be removed:
/data/50-outputs.conf
/data/pfELK/configurations/pipelines.yml.1
/data/pfELK/configurations/05-firewall.conf.save
/data/pfELK/configurations/logstash.yml.1

Next, you do not have the correct pipelines.yml or logstash.yml files; refer to steps 22, 23, and 24.  This is likely the reason you are not receiving any logs as your pipelines.yml is referring to a location that does not contain the necessary files.

Lastly, line 11 within 01-inputs.conf references a routable IP address of 165.45.1.1.  I assume you are masking your IP address but if not let me know as logs received or that traverse through a router will not filter correctly.

**Comment by BoatwrightJA** [comment]
[error.pfelk.log](https://github.com/3ilson/pfelk/files/4613447/error.pfelk.log)

Removed the misplaced files and got the correct .yml files in there location.  

Restarted the services and nothing still. 

Not masking the IP.  That's what I assigned to the pfsense.

**Comment by a3ilson** [comment]
@BoatwrightJA  - 

First, make sure you are receiving logs via tcpdump, ```sudo tcpdump -A port 5140``` if your receiving logs, great... You'll likely need to make the following adjustment within 01-inputs.conf assuming your running pfSense too (i.e. your 01-inputs.conf file should look identical to the following):


```
# 01-inputs.conf
input {
  udp {
     port => 5140
     tags => ["pf", "firewall"]
  }
  if "pf" in [tags] {
    grok {
      match => { "message" => "<(?<[event][id]>.*)>%{SYSLOGTIMESTAMP:[event][created]} %{DATA:labels}(?:\[%{POSINT:[event][id]}\])?: %{GREEDYDATA:pf_message}" }
    }
    mutate {
      rename => { "[message]" => "[event][original]"}
      remove_tag => "Ready"
    }
  }
}
```

Once you amended the a changes, restart logstash.

**Comment by BoatwrightJA** [comment]
<img width="1630" alt="image" src="https://user-images.githubusercontent.com/59629037/81649438-4bbee780-93fe-11ea-9767-2f5cdd53ef7a.png">


I have made the changes but still no go.

**Comment by revere521** [comment]
That error is stating that elasticsearch died somewhere in the process, restart the elasticsearch with `sudo systemctl restart elasticsearch`

**Comment by BoatwrightJA** [comment]
[error.pfelk.log](https://github.com/3ilson/pfelk/files/4617992/error.pfelk.log)

Still no success.

**Comment by BoatwrightJA** [comment]
I can't even get to the Elasticsearch logs

**Comment by BoatwrightJA** [comment]
Where should the plugin for grok file be?  It's complaining about that now.  

<img width="1620" alt="image" src="https://user-images.githubusercontent.com/59629037/81737662-70e74080-9466-11ea-9d8a-7c7d5b1f9ff7.png">

**Comment by BoatwrightJA** [comment]
<img width="1692" alt="image" src="https://user-images.githubusercontent.com/59629037/81747829-c592b780-9476-11ea-88d6-700770e8eaf8.png">

**Comment by revere521** [comment]
Ok, lets go through the config as listed in the error.pflek.log point-by-point and make some corrections: 

1. these folders are extraneous and can be deleted: 
```
/data/patterns
/data/cofigurations
/data/GeoIP
/data/logs
/data/templates
```

2. since `.geoipupdate.lock` still exists in `/data/pfELK/GeoIP/` the geoipupdate process may not have completed again - it can be a big download that takes a few minutes so delete `.geoipupdate.lock` and run geoipupdate again, and allow it to finish

3. 01-inputs.conf looks OK
4. 05-firewall.conf looks OK, but at some point after this is all running you will need to chnage the interface names, interface alias and network names to match your actual interfaces

5. 10-others.conf looks OK
6. 20-suricata.conf looks OK (you can delete it if you don't have suricata running on pfsense)
7. 25-snort.conf looks OK (you can delete it if you don't have snort running on pfsense)
8. 30-geoip.conf looks OK
9. 35-rules-desc.conf needs to be setup following the configuration guide if you want that visulization to work in the firewall dashboard - but thats secondary to whats happening now
10. 40-dns.conf looks OK, but you can delete it if it generates lots of DNS requests - no dashboards currently utilize its data capture
11. 45-cleanup.conf looks OK
12. 50-outputs.conf looks OK

13. this may be the reason you are having the running restart in Logstash - in the Pipelines.yml
remove the spaces before path.config - logstash is most likely interpreting the space as a character

it should look like this: 
```
#   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html

- pipeline.id: main
path.config: "/data/pfELK/configurations/*.conf"
```

14. Java is all set



Check those things and restart all three services
```
sudo systemctl restart elasticsearch
sudo systemctl restart logstash
sudo systemctl restart kibana
```

then run: 

`sudo journalctl -u logstash -n 50 -f`

and watch the log output for logstash and make sure its not continuously restarting

**Comment by BoatwrightJA** [comment]
<img width="1514" alt="image" src="https://user-images.githubusercontent.com/59629037/81752219-0f7f9b80-947f-11ea-8a1e-f2ec29543383.png">

**Comment by BoatwrightJA** [comment]
what's the permission set for the file?

**Comment by revere521** [comment]
that permission is correct, 

go ahead and add the 2 spaces back in front of the path.config line, i gave you bad advice there - i apologize, then restart logstash and review the journalctl output. 

it shouldn't say it can't read pipelines.yml anymore

**Comment by BoatwrightJA** [comment]
No worries.  I appreciate the help.  But back to square one.  

<img width="1496" alt="image" src="https://user-images.githubusercontent.com/59629037/81754112-57082680-9483-11ea-8ba0-f2f79955c044.png">

**Comment by revere521** [comment]
does your logstash.yml match the one in the repo: https://github.com/3ilson/pfelk/blob/master/logstash.yml?

specifically the `path.data: /var/lib/logstash`

**Comment by revere521** [comment]
also, there might be a syntax error in 01-inputs.conf

try removing the line `remove_tag => "Ready"`

since @a3ilson gave you the trimmed down input config, you aren't adding the tag "Ready" anymore - that's in the grok section of the input, so it might be throwing the illegal exception - logstash errors are tough to read. 

this might fix it: 

```
# 01-inputs.conf
input {
  udp {
     port => 5140
     tags => ["pf", "firewall"]
  }
  if "pf" in [tags] {
    grok {
      match => { "message" => "<(?<[event][id]>.*)>%{SYSLOGTIMESTAMP:[event][created]} %{DATA:labels}(?:\[%{POSINT:[event][id]}\])?: %{GREEDYDATA:pf_message}" }
    }
    mutate {
      rename => { "[message]" => "[event][original]"}
    }
  }
}
```

**Comment by BoatwrightJA** [comment]
Yes.  Just more errors.  

<img width="1488" alt="image" src="https://user-images.githubusercontent.com/59629037/81754935-5e303400-9485-11ea-9269-6fd6d842942a.png">

**Comment by a3ilson** [comment]
Did you perform step number 28?

sudo chmod 777 /data/pfELK/logs

**Comment by BoatwrightJA** [comment]
Yes I did .

**Comment by revere521** [comment]
did you try removing that line i noted above from the 01-inputs.conf?

**Comment by BoatwrightJA** [comment]
I did.

**Comment by a3ilson** [comment]
Try removing all the log files from within /data/pfelk/logs

**Comment by BoatwrightJA** [comment]
> Try removing all the log files from within /data/pfelk/logs
> […](#)

There are gone.

**Comment by a3ilson** [comment]
Here is an older thread regarding the save problem.  It is specific to
logstash and a permission issue.

Make sure the log path is correct
Make sure the log path is writable
Make sure only one instance of logstash is running

https://github.com/elastic/logstash/issues/7050

**Comment by BoatwrightJA** [comment]
[error.pfelk.log](https://github.com/3ilson/pfelk/files/4619667/error.pfelk.log)

**Comment by a3ilson** [comment]
The issue is with logstash. Remove logstash and reinstall (i.e. sudo apt-get purge logstash, followed by sudo apt-get install logstash). Next re-accomplish steps 22-24 and see if that works.

**Comment by BoatwrightJA** [comment]
<img width="1791" alt="image" src="https://user-images.githubusercontent.com/59629037/81771698-b2510d80-94b1-11ea-8f91-1533464ac6f7.png">


same messages.

**Comment by BoatwrightJA** [comment]
[conf.txt](https://github.com/3ilson/pfelk/files/4619844/conf.txt)

Can you check to see is something is missing?

**Comment by revere521** [comment]
I can't see anything is missing, i would try to reinstall logstash as @a3ilson suggested, or start over from the beginning.  Its really starting to look like a deeper issue than the config

**Comment by revere521** [comment]
also looks like the 7.7.0 version updated rolled out today, may be worth just starting over

**Comment by BoatwrightJA** [comment]
Sure no problem.  I’ll let you know how it turns out.

**Comment by peter301** [comment]
Hello gents, I have the same issue as described above, but with less errors :)
Neverthless I dont see the pattern in Kibana, even the logs are being sent from PFSENSE.
Here is the log:
[error.pfelk.log](https://github.com/3ilson/pfelk/files/4629184/error.pfelk.log)

I suppose, that there might be issue with logstash, not sure if those errors could be ignored.
Could you please advise, help? thank you !

====================================================
peter@peter-microserver:~$ systemctl status logstash.service
● logstash.service - logstash
   Loaded: loaded (/etc/systemd/system/logstash.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2020-05-14 16:56:42 CEST; 20s ago
 Main PID: 12594 (java)
    Tasks: 19 (limit: 4915)
   CGroup: /system.slice/logstash.service
           └─12594 /usr/bin/java -Xms1g -Xmx1g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -Djava.awt.headless=true -Dfile.encoding=UTF-

máj 14 16:56:42 peter-microserver systemd[1]: logstash.service: Scheduled restart job, restart counter is at 847.
máj 14 16:56:42 peter-microserver systemd[1]: Stopped logstash.
máj 14 16:56:42 peter-microserver systemd[1]: Started logstash.
máj 14 16:56:42 peter-microserver logstash[12594]: OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
**máj 14 16:56:44 peter-microserver logstash[12594]: WARNING: An illegal reflective access operation has occurred
máj 14 16:56:44 peter-microserver logstash[12594]: WARNING: Illegal reflective access by com.headius.backport9.modules.Modules (file:/usr/share/logstash/logstash-core/lib/jars/jruby-complet
máj 14 16:56:44 peter-microserver logstash[12594]: WARNING: Please consider reporting this to the maintainers of com.headius.backport9.modules.Modules
máj 14 16:56:44 peter-microserver logstash[12594]: WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
máj 14 16:56:44 peter-microserver logstash[12594]: WARNING: All illegal access operations will be denied in a future release**

====================================================

**Comment by revere521** [comment]
@peter301 you should open a new issue for yourself and we can help you. 

Part of the problem looks like you folder structure got out of hand.  you may want to check that all the config files are in /data/pfELK/configurations,  the pattern (.grok) is in /data/pfELK/patterns, and the template file is in /data/pfELK/templates

**Comment by revere521** [comment]
@BoatwrightJA how did you make out?

**Comment by BoatwrightJA** [comment]
So I am trying the docker way but it's not making sense.  The instruction of the video is completely different that the GitHub.

**Comment by revere521** [comment]
are you building this for your homelab, or to monitor a single pfsense instance with a single elk server?  if so, i would use the manual or scripted install.   

Docker can be useful in some situations, but it adds a layer of complexity when you might not need to.

**Comment by BoatwrightJA** [comment]
A homelab.

**Comment by revere521** [comment]
@fktkrt can probably shed some light on docker if you want to keep going that way to learn how it all works; but I also use this to monitor my homelab (pfsense to ELK on a small hardware server) - and i personally think the manual or scripted install are the easiest ways to get this running.

**Comment by fktkrt** [comment]
I can recommend all the deploy solutions at the scale of a homelab, however at production level, I would stick to install it either manually or with the ansible-playbook (I was not involved in the making of the shell script, but many had success with it).

If you have experience with ELK stack, you can try deploying with the ansible-playbook, currently that is the closest to a vanilla ELK setup (in terms of folder structure).

If you are new to ELK, you can try the manual/scripted method (which you already did), but pay close attention to the reworked structure of the config files.

If you have the basics of Docker containers and the ELK stack, you can experiment with the docker setup, but that on still a WIP (or at least far from production readiness) and as @revere521 said, introduces one more layer of complexity.
The video might be out-dated, I'd follow the instruction in the docker repo's README and/or you can check its [CI pipeline](https://travis-ci.org/3ilson/docker-pfelk) to get a better understanding of pulling it together.

Choose any of the aforementioned methods and if you experience any issues, feel free to reach out in their corresponding repositories by opening an issue.

**Comment by BoatwrightJA** [comment]
I have experience with all methods but what concerns me is out dated material is out there.  So where can I find the most updated version? Not trying to be a pain but I really like the idea and want to see it work in my homlab environment.

**Comment by fktkrt** [comment]
You can always find the latest instructions in the given repository’s main README.md on master branch.

**Comment by BoatwrightJA** [comment]
So I am asked to modify the GeoIP.conf but it's not located there.  

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/59629037/82499661-15e5c700-9ac0-11ea-9805-eeeb14edcb39.png">

**Comment by revere521** [comment]
Did the `sudo apt install geoipupdate` command succeed?
by default mine is:  `/etc/GeoIP.conf` you look like you are editing a different file in a different directory

![image](https://user-images.githubusercontent.com/23560313/82501318-10d64700-9ac3-11ea-8713-55f8c88a2d03.png)

**Comment by BoatwrightJA** [comment]
Found it after running that command again, thanks.

**Comment by BoatwrightJA** [comment]
Well any ideas?   

I can't load the pf* for indexing. 

[error.pfelk.log](https://github.com/3ilson/pfelk/files/4660070/error.pfelk.log)

**Comment by a3ilson** [comment]
@BoatwrightJA - your pipelines.yml needs to point to the configuration files (reference: steps 22-24).  Once you've made those changes restart logstash and try again.

**Comment by BoatwrightJA** [comment]
should it be pointing to that file path cause nothing is there when I move the the dir. 

<img width="554" alt="image" src="https://user-images.githubusercontent.com/59629037/82513472-1d699800-9ae1-11ea-967f-7ea6822c38a7.png">

**Comment by a3ilson** [comment]
It should look like this file: https://github.com/3ilson/pfelk/blob/master/pipelines.yml

**Comment by BoatwrightJA** [comment]
Are these file to be here? 

<img width="763" alt="image" src="https://user-images.githubusercontent.com/59629037/82515995-af749f00-9ae7-11ea-8fe3-8648e6bc13f4.png">

**Comment by BoatwrightJA** [comment]
Logstash is yelling about something but not sure.  As to this time, I followed the manual automation method. 

<img width="1714" alt="image" src="https://user-images.githubusercontent.com/59629037/82517295-c9fc4780-9aea-11ea-80ff-5c343a11474d.png">

**Comment by a3ilson** [comment]
In world highly recommend the scripted install. Please give the scripted
install a try.  I’ll put together an updated tutorial to assist in the next
day or two.

**Comment by BoatwrightJA** [comment]
I have that what I have tried this time.  It went smooth with out any errors. But know I don't know.

**Comment by solaris04** [comment]
I have the same issue with the pf-* pattern.
I did the manual install first, didnt work. deleted all files and configs and used the script.
Still having the same issue.

Firewall System (please complete the following information):
    OPNSense
    V 20.1.7
    IP of firewall: 192.168.1.1
    VM running ELK is on same subnet and can reach other clients


Operating System:
Virtual Machine GNU/Linux 4.15.0-99-generic x86_64
NAME="Ubuntu"
VERSION="18.04.4 LTS 

Elasticsearch, Logstash, Kibana (please complete the following information):
(dpkg -l elasticsearch|logstash|kibana)
Elastic search 7.7.0
logstash 1:7.7.0-1
Kibana 7.7.0

cat /etc/logstash/pipelines.yml
- pipeline.id: main
  path.config: "/data/pfELK/configurations/*.conf"


No packets are captured with tcpdump -A port 5140

[pfelk error log.txt](https://github.com/3ilson/pfelk/files/4668916/pfelk.error.log.txt)
[sudo journalctl -u logstash -n 50 -f.txt](https://github.com/3ilson/pfelk/files/4668918/sudo.journalctl.-u.logstash.-n.50.-f.txt)
[01-inputs.conf.txt](https://github.com/3ilson/pfelk/files/4668919/01-inputs.conf.txt)



Status of services:
elasticsearch: active
kibana: active
logstash: active with error, see log journalctl



Attachments:
01-inputs.conf
journalctl -u logstash -n 50 -f log
pfELK Error Log (error.pfelk)


Please let me know if you need any more information

**Comment by revere521** [comment]
@solaris04  Please open a new issue so we can assist you.  even if you are seeing the same kind of issue as this one - its a very general error that could be caused by a variety of things.   It becomes difficult to troubleshoot differentiating between two or more people. 

please also run the troubleshooting script again, the output you posted is truncated.

**Comment by a3ilson** [comment]
@BoatwrightJA - Please give the new script install method a try.  I just tested on Ubuntu Server 20.04 w/8GB ram and 32GB HD.  Worked without any issues.

**Comment by revere521** [comment]
I'm testing the script on an Ubuntu 18.04.4 server and a Debian 10 server, I'll open an issue with my feedback to keep it separate

**Comment by BoatwrightJA** [comment]
Hi @a3ilson,

Thanks for going out of you way to do that. Very much appreciated!

I will test out the new script today.  

Do I need to remove anything before I get stated?  My gut feeling tells me no but want to make sure.

**Comment by a3ilson** [comment]
I would recommend a clean install.

**Comment by a3ilson** [comment]
@BoatwrightJA - have you had any success?

**Comment by BoatwrightJA** [comment]
unfortunately, it's not working for me.  I'm sure it's on my end and sure nothing wrong with what you have scripted.

**Comment by a3ilson** [comment]
What was the resulted error?  How much RAM do you have allocated?
