### ISSUE TITLE
Cannot import Dashboard (Docker install)

### ISSUE THREAD

**Issue by Fetakungen** [pfelk/pfelk#130]
Hi i'm totally new to Kibana so i'm probably missing something basic, but when trying to import the Dashboard i get this error..
"Index Pattern Conflicts

The following saved objects use index patterns that do not exist. Please select the index patterns you'd like re-associated with them. You can create a new index pattern if necessary.
Sorry, there was an error"

I chose pf-*

But then get:
The file could not be processed.

See picture below.

https://cloud.gabenpirates.com/index.php/apps/files_sharing/publicpreview/sPjQzDBmakfFFS3?x=1905&y=806&a=true&file=Import.PNG&scalingup=0

What am i missing ?

**Comment by revere521** [comment]
Is it just the Suricata Dashboard?  are you using this one: https://github.com/3ilson/pfelk/blob/master/Dashboard/v4.3%20(062020)%20Suricata%20Dashboard.ndjson  ?

**Comment by Fetakungen** [comment]
i tried all of them.

**Comment by revere521** [comment]
it looks like you already created the index pattern (under management -> index patterns) so that should be good to go. 

When you import them, are you dragging and dropping the file with the .ndjson extension? (not a zip or anything like that).

The only other thing i can think of is to try and restart the containers and try again, I havn't seen that issue before and I just re-imported the containers to make sure the files look good.  

Otherwise @fktkrt may have a suggestion for how to troubleshoot the docker containers better

**Comment by Fetakungen** [comment]
I tried both pointing and dragging. Also I did git clone just to be sure that nothing happened when i saved the .ndjson but same error. =/

**Comment by revere521** [comment]
what versions of ELK does the docker install? it could be a version mismatch (the dashboards are from newer versions of Kibana possibly)

could there be anything impeding uploads to Kibana as well? Is the docker install on your local network?  or do you need to do something in the cloud that would limit uploads?

**Comment by a3ilson** [comment]
How are you importing? Please provide detailed steps.

**Comment by Fetakungen** [comment]
hi i dunno what was the cause but i git cloned a new master and it worked from the box :S
