### ISSUE TITLE
pfelk on Raspberry Pi 4

### ISSUE THREAD

**Issue by ledge39** [pfelk/pfelk#134]
I have installed ELK 6.8.10 on Raspberry Pi 4 (8GB) and imported your logstash config, which is working well.
The only thing I can't work out is how to import the Dashboards. The saved objects import doesn't seem to like the ndjson format. Any ideas?

**Comment by revere521** [comment]
I think post version 7 of the ELK stack they switched to .ndjson from .json format;  if possible try to get the pi to the current versions (7.8)

This may be a heavy lift for a pi though, even the Pi4 only has half the recommended amount of memory (8gb) so your mileage may vary here.

If 7.8 isn’t possible on the pi, you may be able to use old json dashboards in the archive (if they still exist) as a launching point to building new ones.

**Comment by a3ilson** [comment]
@ledge39 - were you able to update and/or install ELK 7+

**Comment by dsantanu** [comment]
just for the Info - I actually tried a VM with 8G RAM on QNAP - Elasticsearch wasn't even starting

-S

**Comment by revere521** [comment]
I run it on a old i5 with 8gb of ram in my home lab with no issues, so that shouldn't be a resources issue.  The Pi may work, depending on how much data you throw at it, but you will probably need to build your own dashboards. 

I see that the ELK stack is now 64bit, and I don't see any arm architecture in the repos, so that may be the limitation. 

I just bought an old referb HP Elitedesk 8000 series on newegg for $125 USD or so.  If you are just expirimenting, an old referb business machine is the way to go.  Save the Pi for something more fun like NES emulation :)

**Comment by fktkrt** [comment]
@dsantanu Were you able to test this with newer ELK versions?

**Comment by ledge39** [comment]
Unfortunately, I can get not work Kibana 7+ to work.

**Comment by dsantanu** [comment]
> @dsantanu Were you able to test this with newer ELK versions?

tested with V7. It vastly depends on the CPU - an i5 probably okay but QNAP with 1.60GHz Celeron N3160 couldn't cope.  Finally gave up on QNAP and used a spare R210.

**Comment by ledge39** [comment]
Have changed approach now going with Elasticsearch 6.8.10 and Graylog 3.3.2.

**Comment by kekkers23** [comment]
> Have changed approach now going with Elasticsearch 6.8.10 and Graylog 3.3.2.

Sorry to necro this github has no pm...

Did you manage to setup Graylog on a RPI?
