### ISSUE TITLE
Guidance for integrating an existing pfSense router and Elastic Stack?

### ISSUE THREAD

**Issue by squirrelboot** [pfelk/pfelk#264]
Hello!

I am very excited about your project. It looks amazing, and it's exactly what I am looking for. 
ElasticSearch is very new to me, and I could use some help.

I have installed/configured my ElasticSearch system based on the Wazuh All-in-one deployment ([Link](https://documentation.wazuh.com/4.0/installation-guide/open-distro/all-in-one-deployment/all_in_one.html)).

If I already have a pfSense router running, and an existing Elastic Stack installed:
Where and how would I start to install/configure your pfelk, so that I could use it with the existing installation?

Thank you for any guidance you can provide

**Comment by squirrelboot** [comment]
For example there are some questions during the installation I am not sure about.
Also, when trying it once, it breaks the wazuh-elastic connection somehow. 
Also it asks about different java things

**Comment by a3ilson** [comment]
@squirrelboot - I'll attempt to break down your compound questions:

1.  Please specify *some question during the installation* which you are unsure about
2. Please clarify what *different java things* you are referring too
3. Providing assistance on here about Wazuh would yield similar results inquiring into pfelk on Wazuh but we can get you pointing in the right direction.

### Overview
#### The Wazuh deployment is comprised of three components:
- Elasticsearch
- Beats
- Kibana

#### pfelk is comprised of three components:
- Elasticsearch
- Logstash
- Kibana

Both require *feeding* (i.e. logs from external sources).

Here are a couple of conceptual solutions:
1.  You'd likely need to install logstash on your Wazuh instance but would likely need to adjust the ports in which logs are received so that they do not conflict/compete with Beats. Additionally, pfelk listens on port 5044 (01-inputs.conf) and would require competing out, so that it would not conflict with Wazuh.
2.  You could install a separate instance with just Logstash (for pfelk) having those logs sent to the Wazuh Elasticsearch instance for indexing and visualizations via Kibana. The only revision here would be designating the Elasticsearch within the 50-outputs.conf file.

**Comment by a3ilson** [comment]
Not a pfelk related issue
