### ISSUE TITLE
Missing Snort Index, Template and Dashboard

### ISSUE THREAD

**Issue by darvinrivera** [pfelk/pfelk#266]
**Describe the bug**
I use pfSense.
I have the last version, updated today, when i try to check Snort Discovery i didnt see the filter (snort-filter*). I check index template and is missing, i check Save Objects and Dashboard is missing. I try to reintall all index (manual and automatic) and still missing Snort index, i try reinstall dashboard automatic and is missing complete Snort dashboard, only when i import dashboard (manual) appear Snort Flow.
Captive Portal, Firewall, Unbound and DHCP is working perfect.
Need help to bring back Snort.

**Screenshots**
Snort Index is Missing
![Snort Index is Missing](https://user-images.githubusercontent.com/17580342/107967039-a03d5780-6f7a-11eb-92d1-cf3f2da6c92d.png)

Snort Index Template
![Snory Index Template](https://user-images.githubusercontent.com/17580342/107967075-acc1b000-6f7a-11eb-87ed-c2dfd61bb39f.png)

Snort Templates
![Snort Templates](https://user-images.githubusercontent.com/17580342/107967105-b6e3ae80-6f7a-11eb-9162-60361b70478b.png)

**Comment by a3ilson** [comment]
@darvinrivera - Please describe how you installed the dashboard (saved objects).

**Comment by a3ilson** [comment]
@revere521 and/or @darvinrivera 

The latest [snort saved object](https://raw.githubusercontent.com/pfelk/pfelk/master/Dashboard/v20.2/v20.2-Snort.ndjson) contains all the visualizations but does not include the snort-index pattern (kibana).


I do not utilize snort and limited in correcting this but the following will work:

## Step 1
### Delete snort objects

- Navigate to Stack Management>>Saved Objects(under the Kibana header)
- Type `snort` in the search field and press enter (this should filter on all/any snort objects)
- Select all the snort objects (checkbox to the left)
- Click on Delete (this will remove all snort objects)


## Step 2
### Create snort index (kibana)

- Navigate to Stack Management>>Index Patterns(under the Kibana header)
- Click on Create Index Pattern (upper right)
- input/type, `pfelk-snort-*` and click next step
- Select `@timestamp` under the time field
- Input `pfelk-custom-snort-ID` within the custom index pattern ID
- Click Create Index Pattern (lower right)

## Step 3
### Import snort.ndjson file

- Download and install the [snort.ndjson](https://raw.githubusercontent.com/pfelk/pfelk/master/Dashboard/v20.2/v20.2-Snort.ndjson) file 
- Navigate to Stack Management>>Saved objects(under the Kibana header)
- Click on import (upper right)
- Import the snort.ndjson file
- You may need to specify the snort index pattern
  - ![Screen Shot 2021-02-15 at 12 15 42](https://user-images.githubusercontent.com/16884679/107976440-8f471300-6f87-11eb-8e9e-b051f4ef1e18.png)
- Click on the new index and select the pfelk-snort-* index pattern

## Step 4
### Test
- Navigate to the snort dashboard and check to see if it is working

## Step 5
### Contribute
- Now that it is working please create the ndjson file (saved objects), so that we can update the repo and help others.
- Navigate to Stack Management>>Saved objects(under the Kibana header)
- Type `snort` in the search field and press enter (this should filter on all/any snort objects)
- Select all the snort objects (checkbox to the left...be sure that the index pattern is included)
- Click Export, unselect `include related objects` and click export
- This will save a .ndjson file containing all snort items
- Test
  - Delete all snort items (Step 1)
  - Import the new file from Step 5
  - Check to make sure everything is working (snort)
  - Post new file here and or submit a PR

**Comment by darvinrivera** [comment]
Manual: Only add Snort-Flow Visualization
Stack Managment-> Save Objects-> Import -> Select Download Dhasboard from repo.- -> Automatic overrride conflicts.
Now i see this here... Missing pfelk-snort.
![Snort Import](https://user-images.githubusercontent.com/17580342/107977112-991d4600-6f88-11eb-81bc-9c07b19dd7a5.png)

**Comment by a3ilson** [comment]
@darvinrivera - Those are *Saved Objects* please reference my previous response (step 2)

**Comment by squirrelboot** [comment]
Hi, can anyone add to this with that export? 
I did a fresh pfelk install on a debian server. I was missing the snort entries as well. 

This process you illustrated in the above steps fixed it for me. I have the export for it as well:
[snort_my_export.zip](https://github.com/pfelk/pfelk/files/5983267/snort_my_export.zip)

I literally jaw-dropped when I saw the page load and the data came through. :)

**Comment by darvinrivera** [comment]
@a3ilson Sorry i answering without see your next post.
I follow ALL your steps and is working...
Here is my Dashboard working (including index config): [Snort-20.2a.zip](https://github.com/pfelk/pfelk/files/5983287/Snort-20.2a.zip)

**Comment by squirrelboot** [comment]
@darvinrivera Could you post the same thing but for suricata in step 5? 

I think it is the exact same problem, but I don't have the suricata version of the snort.ndjson file from step 3

**Comment by squirrelboot** [comment]
@a3ilson- Could you please supply the 'Suricata version' of the snort.ndjson file from step 3?
I am having the same problem but with Suricata. 
Thank you.

**Comment by a3ilson** [comment]
> @a3ilson- Could you please supply the 'Suricata version' of the snort.ndjson file from step 3?
> I am having the same problem but with Suricata.
> Thank you.
Here ya go...but if your still having issues, let's open another issues as it appears the original issue was resolved/fixed.

https://github.com/pfelk/pfelk/blob/master/etc/pfelk/dashboard/v20.2-suricata.ndjson

**Comment by darvinrivera** [comment]
This is my Suricata Dashboard working: [Suricata-20.2a.zip](https://github.com/pfelk/pfelk/files/5983355/Suricata-20.2a.zip)

**Comment by a3ilson** [comment]
> This is my Suricata Dashboard working: [Suricata-20.2a.zip](https://github.com/pfelk/pfelk/files/5983355/Suricata-20.2a.zip)

@squirrelboot - are you good to go?

@darvinrivera - thanks!

**Comment by squirrelboot** [comment]
It resolved the issue for snort. Raising a new ticket for different suricata issue. 
Thanks
