### ISSUE TITLE
Issue importing firewall dashboard

### ISSUE THREAD

**Issue by Makss39** [pfelk/pfelk#319]
First, thanks for the good job !
I was able to set it up easyl on my existing ELK stack without any trouble, great doc !

The only stuff which is not working is the import of the firewall.ndjson dashboard.
(DHCP, Squid, Surricata are OK...)

I get the following error message : `The file could not be processed due to error: "Unprocessable Entity: Document "id-firewall" has property "index-pattern" which belongs to a more recent version of Kibana [7.11.0]. The last known version is [7.6.0]"`

I'm using version 7.10.2 of the stack...

Thanks for your kind help !

**Comment by revere521** [comment]
The current version of the stack (as of today) is 7.13.4,  unless there is a compelling reason not to update – I would just update the versions of elasticsearch, logstash and kibana with your package manager.

I am running 7.13.3 with the current config in the repo with no issues (and will be updating myself to 7.13.4 shortly)

From: Makss39 ***@***.***>
Sent: Tuesday, July 20, 2021 9:26 AM
To: pfelk/pfelk ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [pfelk/pfelk] Issue importing firewall dashboard (#319)


First, thanks for the good job !
I was able to set it up easyl on my existing ELK stack without any trouble, great doc !

The only stuff which is not working is the import of the firewall.ndjson dashboard.
(DHCP, Squid, Surricata are OK...)

I get the following error message : The file could not be processed due to error: "Unprocessable Entity: Document "id-firewall" has property "index-pattern" which belongs to a more recent version of Kibana [7.11.0]. The last known version is [7.6.0]"

I'm using version 7.10.2 of the stack...

Thanks for your kind help !

**Comment by Makss39** [comment]
Thanks for the fast answer !

I know that i'm not up to date, but i've several stuff on my stack and i would prefer to keep it on 7.10.2 for now...
So no idea why it stuck ?

**Comment by a3ilson** [comment]
@Makss39 - it would be best to upgrade. Unfortunately, once we move on we just do not have the bandwidth or demand to support legacy versions.

**Comment by Makss39** [comment]
Dashboard is OK on 7.14 !

Thanks
