### ISSUE TITLE
After upgrading the elastic version, the graphs seem to show incorrectly.

### ISSUE THREAD

**Issue by gokhansezen** [pfelk/pfelk#330]
After upgrading the elastic version, the graphs seem to show incorrectly.

Elastic version 7.14.0
Pfsense 2.5.2
Ubuntu 20.04.2 LTS

![Screenshot_20210814-132124~2](https://user-images.githubusercontent.com/16643176/129443631-167395ba-afa9-4cd0-a6e0-1d9b0a969e13.png)

**Comment by revere521** [comment]
It looks like the changed some of the labeling options for the donut graph.    Its "fatter" by default now - i don't see an option in the visualization to change the thickness.  They appear to have added a "nest legend" option that you can turn on to show a hierarchy for the split slices: 

![image](https://user-images.githubusercontent.com/23560313/129445881-4e1f570e-4ffa-47bb-999e-9d77015aba0f.png)

that gives you a legend like: 

* Pass
  * LAN
  * WAN
* Block
  * WAN

so to see the legend for both levels you may need to edit the visulization and turn that on

Otherwise, its still visualizing the correct data

**Comment by gokhansezen** [comment]
Thanks bro. Problem solved thanks to you.
