### ISSUE TITLE
Geo panels on Firewall Dashboard do not populate

### ISSUE THREAD

**Issue by imagesafari** [pfelk/pfelk#409]
**Describe the bug**
The firewall dashboard is not populating the geo panels. The "destination.geo.country_name" data is there when I inspect the details in the log table further down the dashboard.

**Screenshots**
As an example, at the top:

![image](https://user-images.githubusercontent.com/395969/153781591-12b183ff-f537-4379-a2f1-de85aa8d6e94.png)

**Firewall System (please complete the following information):**
 - OPNsense 21.7.7-amd64
 
**Operating System (please complete the following information):**
 - OS (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):
 
 **Installation method (manual, ansible-playbook, docker, script):**
Docker + Manual dashboard imports, etc

**Comment by imagesafari** [comment]
And just after I submit this, poking into the dashboard (I'm not a Kibana guru), it looks like the data field is actually "destination.geo.geo.country_name" and if I modify it, it works. I'm not sure where the extra geo is coming from.

**Comment by swiftbird07** [comment]
Well I was just about to post the same kind of question lol. 
This double naming also is inside i.e.  _destination.as.**as**.organization.name_ which will result in the fact that elastic does not allow me to work with these fields in any way. e.g. if I try to whitelist something like that from Elastic SIEM I can't do that because "_Lists and non-ECS fields are not supported_".
I thought I was the only one messing this up but now that I see your post it seems like amore common issue. 
@imagesafari Are you also on ELK v 8.0?

**Comment by a3ilson** [comment]
@imagesafari - can you confirm the Elastic version that you are running? 

The duplicated geo.geo and as.as were caused by the latest update (v8.0.0). Updating your 30-geoip.conf and restarting logstash will correct the duplication and the dashboards will work thereafter.

- [ ] The v8.0.0. broke the GeoIP Points for those utilizing maps <-- will open separate issue

**Comment by imagesafari** [comment]
Elastic 8.0.0

**Comment by a3ilson** [comment]
@imagesafari - please advise if the updated 30-geoip.conf and pipelines.yml corrected the issue.

**Comment by imagesafari** [comment]
Yes, it seems to have done the trick. Thanks!
