### ISSUE TITLE
ElasticSearch fails to install using newest code release 3/422

### ISSUE THREAD

**Issue by ghost** [pfelk/pfelk#419]
good luck.

**Comment by nwdean** [comment]
@a3ilson looks like there is a conflicting config setting? It is kind of confusing though because the line is commented out in the elastisearch.yml file. So shouldn't it just ignore this?

Caused by: org.elasticsearch.ElasticsearchSecurityException: invalid configuration for xpack.security.transport.ssl - [xpack.security.transport.ssl.enabled] is not set, but the following settings have been configured in elasticsearch.yml : [xpack.security.transport.ssl.keystore.secure_password,xpack.security.transp$

**Comment by a3ilson** [comment]
@nwdean - depends on where the script exited at. Here's an overview of the script specific to the elasticsearch install:
- Downloads Elasticsearch
- Installs Elasticsearch
- Replaces elasticsearch.yml
- Starts Elasticsearch 

Ideally I wanted to have the *.yml files in place prior to installing but if the file exists during the install, an additional prompt is presented for the user to keep the original, replace etc... wanted to keep it simple I decided to place this after the initial install and prior to elasticsearch starting.

I've done four installs since but haven't been able to replicate your specific error. I'll tinker with it more this weekend and revise my VM for 8GB of ram trying to mimic your setup as I suspect the ram to be the possible issue (8GB for elasticsearch is the minimum and although you have 8GB, the OS will consume some and after logstash and Kibana are installed, you might be pushing the limit)

**Comment by nwdean** [comment]
@a3ilson I have been trying to figure this one out and it is even more confusing, even though it has an explicit error that I added above.

Those conflicting attributes aren't even in the elasticsearch.yml file. Where is it getting those from? weird

**Comment by nwdean** [comment]
@a3ilson also I am not concerned with the memory issue just yet. When this was running under the 7.x version the memory wasn't fully consumed. Everything was running normal. With the 8.x version of things the process won't even run because of this error

**Comment by nwdean** [comment]
@a3ilson BOOM! got it.

those settings are in the elasticsearch.keystore file. There is a program with a command you can run to edit it and remove those settings
Link to where I found the answer: https://discuss.elastic.co/t/invalid-configuration-for-xpack-security-transport-ssl/297989

commands:
to list: /usr/share/elastisearch/bin/elastisearch-keystore list
to show values before deleting: /usr/share/elastisearch/bin/elastisearch-keystore show <name-of-the-setting>
to remove specific setting: /usr/share/elastisearch/bin/elastisearch-keystore remove <name-of-the-setting>

**Comment by a3ilson** [comment]
Awesome!

I’ll add the keystore file to the repo and script. That’s a bit odd that it isn’t a consistent error.
