### ISSUE TITLE
_grokparsefailure dhcpv6 on OPNsense 22.1.2

### ISSUE THREAD

**Issue by hermanops** [pfelk/pfelk#424]
**Describe the bug**
05-apps.conf looks for process.name: dhcp6c, but this doesn't exist in OPNsense 22.1.2. 
dhcpv6 on OPNSense 22.1.2 logs with process.name: dhcpd and this gives a _grokparsefailure in case of dhcpv6 data.

**Firewall System (please complete the following information):**
 - OPNsense 22.1.2_1-amd64
 
 **Installation method (manual, ansible-playbook, docker, script):**
 - manual
 
**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - ELK 8.0.1

**Additional context**

**Comment by a3ilson** [comment]
@hermanops - testing now

**Comment by a3ilson** [comment]
@hermanops - can you provide some ipv6 logs? My ISP does not offer ipv6 yet :(

**Comment by hermanops** [comment]
<190>Mar 12 20:36:05 OPNsense.home.arpa dhcpd[15670]: Reply NA: address fd00:dead:beaf:1::1f2a to client with duid 00:01:00:01:25:84:ae:29:4c:3b:df:63:51:eb iaid = 139213791 valid for 7200 seconds
<190>Mar 12 20:36:05 OPNsense.home.arpa dhcpd[15670]: Sending Reply to fe80::4127:882c:1c28:c9db port 546
<190>Mar 12 20:36:05 OPNsense.home.arpa dhcpd[15670]: Renew message from fe80::4127:882c:1c28:c9db port 546, transaction ID 0xDB1FDB00
<190>Mar 12 20:32:20 OPNsense.home.arpa dhcpd[15670]: Renew message from fe80::dd32:3c8d:d6d0:dc14 port 546, transaction ID 0xDB1F300
<190>Mar 12 20:32:20 OPNsense.home.arpa dhcpd[15670]: Sending Reply to fe80::dd32:3c8d:d6d0:dc14 port 546
<190>Mar 12 20:32:20 OPNsense.home.arpa dhcpd[15670]: Reply NA: address fd00:dead:beaf:1::1f4f to client with duid 00:01:00:01:25:1e:c1:bc:b8:27:eb:36:8d:2e iaid = -345778053 valid for 7200 seconds
<190>Mar 12 20:30:38 OPNsense.home.arpa dhcpd[15670]: Confirm message from fe80::da8c:79ee:fe0d:1b73 port 546, transaction ID 0x16CE2000
<190>Mar 12 20:30:38 OPNsense.home.arpa dhcpd[15670]: Sending Reply to fe80::da8c:79ee:fe0d:1b73 port 546
<190>Mar 12 20:30:06 OPNsense.home.arpa dhcpd[15670]: Sending Reply to fe80::eadf:70ee:fea3:35f4 port 546
<190>Mar 12 20:30:06 OPNsense.home.arpa dhcpd[15670]: Renew message from fe80::fadf:70ee:fea3:35f4 port 546, transaction ID 0xB2685400
<190>Mar 12 20:30:06 OPNsense.home.arpa dhcpd[15670]: Reply NA: address fd00:dead:beaf:1::18f2 to client with duid 00:03:00:01:e8:df:70:a3:35:f4 iaid = 1889744372 valid for 7200 seconds
<190>Mar 12 20:30:02 OPNsense.home.arpa dhcpd[15670]: Sending Reply to fe80::de39:6fee:fe69:fcc8 port 546

**Comment by a3ilson** [comment]
@hermanops thanks! I'll likely have to spend more time on this than originally anticipating (e.g. ensure grok pattern can distinguish between dhcp 4vs6 since OPNsense adjusted all dhcpd to one process where it was previously two.

**Comment by a3ilson** [comment]
I'll be setting up a small DHCP6 instance to gather more logs but slowing working on this.

(https://www.rfc-editor.org/rfc/rfc8415.html)

**Comment by a3ilson** [comment]
@hermanops - I'm getting IPv6 logging without _grokparsefailure...based on your logs and the title of this thread, the issue is dhcpv6. However, looking at past issues and configuration it should be parsing without error.

05-apps.pfelk lines 41-52 push dhcpdv6 logs to the dhcpdv6 grok pattern which is not complete and will simple log the entire message.

However and unfortunately it appears that dhcpdv6 is no longer contained in the message and both v4 and v6 include the same "dhcpd" entry. This mitigates the current grok patterns being able to delicate between v4 and v6. However, I suspect that the number (process ID) immediately following is specific to v6 vs v4. For instance, "15670" are likely all related to v6 whereas "21173" are v4.



~- [ ] Need to confirm that the process ID for OPNsense and pfSense are consistent between the two (i.e. is PID 15670 the same on both OPNsnse/pfSense)~
- [x] Need to fix/finish #403...so that the grok pattern will extract the process ID (PID) from RFC 5424 logs
- [ ] Need to configure 05-apps.conf to delineate v4 & v6 based on PID...if the PID is consistent and the same for pfSense and OPNsense

**Comment by a3ilson** [comment]
@revere521 - can you confirm any DHCPv6 logs from pfSense? 
- Process name (log.syslog.appname)

@hermanops - I've replicated the grok failures and have the following messages:
- Sending Reply to...
- Reply NA: address...
- Renew message from...
- reuse_lease: lease age 3663 (secs) under 25% threshold, reply with unaltered, existing lease for...
- Solicit message from...
- Sending Advertise...
- Confirm message from...
- Picking pool address...
- Wrote 27 NA, 0 TA, 0 PD leases to lease file.
- Wrote 41 leases to leases file.

Do you have any others listed with an associated grokfailure?
