### ISSUE TITLE
Grafana: Elasticsearch error: Bad Gateway

### ISSUE THREAD

**Issue by seebaer1976** [pfelk/pfelk#458]
**Describe the bug**
I installed pfelk on a fresh debian server using a script method. everything is running and all data arrive clean from the firewall. it has the ip: 192.168.30.100

now i want to set up elasticsearch in grafana. only there I can't connect to elasticsearch. it always comes up 'Elasticsearch error: Bad Gateway' when clicking on save & test. I can connect to influxdb with no problems.
the grafana server has the ip: 192.168.30.50

**To Reproduce**

**Firewall System (please complete the following information):**
 - OPNsense
 - 22.7.10_2 
 
**Operating System (please complete the following information):**
 - OS (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):
 - Linux 5.10.0-20-amd64 x86_64
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
 
 **Installation method: script

**Comment by a3ilson** [comment]
@seebaer1976 

A few years ago @b4b857f6ee added an add-on to pfelk utilizing Grafana [here](https://github.com/b4b857f6ee/opnsense_grafana_dashboard). However, it hasn't been updated since Elastic enabled by default the username an password.

I am guessing that the issue may be a result of the default authentication needed for Elasticsearch.
- Have you added a user with the necessary permissions?

Alternatively, you could disable the default authentication for Elasticsearch
