### ISSUE TITLE
invalid links in Custom Installation Guide

### ISSUE THREAD

**Issue by TheFlipside** [pfelk/pfelk#474]
**Describe the bug**
The Custom Installation Guide at https://github.com/pfelk/pfelk/blob/main/install/ubuntu.md has a link at step "9. Configure Kibana" which leads to 404 not found

**To Reproduce**
1. Go to https://github.com/pfelk/pfelk/blob/main/install/ubuntu.md#9-configure-kibana
2. Click on the link
  
 **Installation method (manual):**

**Comment by a3ilson** [comment]
Thank you!

Update/fixed... rather than maintaining the kibana.yml. The following commands will amend the kibana.yml as needed and were updated in the manual instructions.

 sed -i 's/#server.port: 5601/server.port: 5601/'  /etc/kibana/kibana.yml
 sed -i 's/#server.host: "localhost"/server.host: "0.0.0.0"/' /etc/kibana/kibana.yml
