### ISSUE TITLE
Syslog-ng 

### ISSUE THREAD

**Issue by tunavis** [pfelk/pfelk#475]
Hi Guys can someone send me a example of the syslog-ng using certs I have the following certs that needs to be imported somehow in my pfsense: ca.crt, logstash.crt, logstash.pkcs8.key

![image](https://user-images.githubusercontent.com/8057000/231455368-38da964c-ff78-4037-b821-5da94163db69.png)

**Comment by revere521** [comment]
I've never tried securing the traffic in my homelab - but i can help you reason through it.  For syslog-ng to see the certs, you probably have to upload or configure them in pfsense in the certificate manager first under:  System / Certificate Manager 

next in the syslog-ng configuration gui you will be able to select your certificate authority and cert from the drop-downs. 

Since it suggests in the tool-tips that it will use the certs for TLS, i'm not sure if you have to call anything in your source and destination config, but i will look into it.

**Comment by revere521** [comment]
IT looks like the examples for using the TLS cert in the source and destination would be formatted like this: 

Destination  - note the paths/examples are just copied from the tool-tip
```
{
   network("xxx.xxx.xxx.xxx"
   port(5140)
   transport(tls)
   tls(
      ca-dir("/var/etc/syslog-ng/ca.d")
      cert-file("/var/etc/syslog-ng/syslog-ng.cert")
      key-file("/var/etc/syslog-ng/syslog-ng.key")
      peer-verify(optional-trusted)
    )
   );
};
```

it looks like Source would then be formatted something like:
```
{
  wildcard-file(
    base-dir("/var/log/suricata")
    filename-pattern("eve.json")
    recursive(yes)
    follow-freq(1)
    program-override("suricata")
    host-override("pfSense.HOME")
    flags(no-parse)
    tls(
      ca-dir("/var/etc/syslog-ng/ca.d")
      cert-file("/var/etc/syslog-ng/syslog-ng.cert")
      key-file("/var/etc/syslog-ng/syslog-ng.key")
      peer-verify(optional-trusted)
    )
  );
};
```
someone who knows syslog-ng better can probably help, but this looks like the place to start

**Comment by a3ilson** [comment]
@tunavis - I'm using OPNsense which appears to be a little easier to configured.
