### ISSUE TITLE
[geoip] and [ids_src_ip] what are their usage?

### ISSUE THREAD

**Issue by uhlhosting** [pfelk/pfelk#5]
I am curious what is this line serving for?

 if ![geoip] and [ids_src_ip] !~ /^(10\.|192\.168\.)/ {
                  geoip {
                    add_tag => [ "GeoIP" ]
                    source => "ids_src_ip"
                    database => "/usr/share/GeoIP/GeoLite2-City.mmdb"
                  }

I find it in 2 locations in File: 11-pfsense.conf

Thank you!

**Comment by lordcantide** [comment]
Basically, "If a GEOIP does NOT exist and the IDS SRC IP does NOT begin with either "10." or "192.168." (aka LAN Private IP ranges), then attempt to geolocate"
FWIW: The Private IP Ranges in the code do not include all ranges identified in [RFC 1918](https://en.wikipedia.org/wiki/Private_network). If you're a special snowflake like me and have LAN segments in all 3 ranges (don't forget about localhost), you'll need to change the conditional...
`if ![geoip] and [ids_src_ip] !~ /^(127\.|10\.|172\.1[6-9]\.|172\.2[0-9]\.|172\.3[0-1]\.|192\.168\.)/ {`
I do see an argument that this is overkill if you are looking for rogue subnets, but I'm hopefully not going to accidentally find them because of some GeoIP lookup failure. Logically, it is guaranteed that polling geoip for this ranges is just wasting cycles.

**Comment by lordcantide** [comment]
Almost forgot, you mentioned that you found it in 2 locations. Note that the other location is for "source IP"  from Filterlogs and NOT source IP as identified by the IDS. 2 different programs, 2 different tags.
