### ISSUE TITLE
openVPN log 

### ISSUE THREAD

**Issue by camarigor** [pfelk/pfelk#71]
![ok](https://user-images.githubusercontent.com/26566126/74275451-a909a680-4cf2-11ea-82d8-b1fafc70d285.png)
Hey guys, it's me again.

**Is your feature request related to a problem? Please describe.**
When creating new dashboards for openvpn errors i found that this error line use a counter: 

`Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #1280 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings`
`Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #1279 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings`
`Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #1278 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings`

So is impossible to aggregate this as unique error and count.

**Describe the solution you'd like**
Would be awesome if the grok remove that counter before save the event at elasticsearch

**Describe alternatives you've considered**
I have tried to use lucene query's to fix  it but failed.

**Additional context**
No one.

**Comment by revere521** [comment]
Since this is one of many patterns for errors that are possible to collect for that field; its probably not something best handled by the grok.    This is something that Elasticsearch scripting would be better to handle - https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting.html

I can try to look into it, but I can honestly say it will take me some time

**Comment by a3ilson** [comment]
> 
> 
> ![ok](https://user-images.githubusercontent.com/26566126/74275451-a909a680-4cf2-11ea-82d8-b1fafc70d285.png)
> Hey guys, it's me again.
> 
> **Is your feature request related to a problem? Please describe.**
> When creating new dashboards for openvpn errors i found that this error line use a counter:
> 
> `Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #1280 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings`
> `Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #1279 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings`
> `Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #1278 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings`
> 
> So is impossible to aggregate this as unique error and count.
> 
> **Describe the solution you'd like**
> Would be awesome if the grok remove that counter before save the event at elasticsearch
> 
> **Describe alternatives you've considered**
> I have tried to use lucene query's to fix it but failed.
> 
> **Additional context**
> No one.

@camarigor are the previously mentioned logs in their raw format?

**Comment by camarigor** [comment]
Hey @a3ilson its raw format, yes.

**Comment by revere521** [comment]
If you are not worried about the text after the count/tally try adding a colon to the end of the grok for openvpnlog:

`OPENVPNLOG %{GREEDYDATA:openvpn_message}:`

That should stop the collection of that field at the colon

If you want to see if that effects other messages, you can try this to see what happens:

`OPENVPNLOG %{GREEDYDATA:openvpn_message1}:{GREEDYDATA:openvpn_message2}`

Otherwise, you will need to look at some kind of script to mutate the field and remove numerals or characters between the brackets.  I did a little ready, but its been busy so I haven't found a more elegant solution yet.

**Comment by a3ilson** [comment]
@camarigor - did the alternative provided by @revere521 work and/or suffice your needs?

**Comment by camarigor** [comment]
Hey guy sorry my delay. I'll check it today.

**Comment by revere521** [comment]
are we all good here?

**Comment by a3ilson** [comment]
@camarigor - This should also work: ```%{GREEDYDATA:[openvpn][log][message]}:\s%{GREEDYDATA:[openvpn][sequence][number]}\s--\s%{GREEDYDATA:[openvpn][log][remarks]}``` along with the previous examples provided by @revere521 

Please confirm and close.

**Comment by revere521** [comment]
I'm going to assume one of the 3 provided solutions here will work, and close this since we haven't heard from @camarigor for 2 weeks.

**Comment by camarigor** [comment]
Hey guys. Sorry my giant delay. Corona change much things here. I hope everyone is ok. i'll test it today. Give me some hours.
